"use client";

import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";

// 1. Create Styles (CSS for PDFs is slightly different)
const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontFamily: "Helvetica",
        fontSize: 12,
        lineHeight: 1.5,
    },
    header: {
        marginBottom: 20,
        borderBottom: "1px solid #ccc",
        paddingBottom: 10,
    },
    companyName: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#1e293b", // Slate-800
    },
    clientName: {
        fontSize: 14,
        color: "#64748b", // Slate-500
        marginTop: 5,
    },
    body: {
        marginTop: 20,
        color: "#334155", // Slate-700
        whiteSpace: "pre-wrap", // Keeps the AI formatting (newlines)
    },
    footer: {
        position: "absolute",
        bottom: 30,
        left: 40,
        right: 40,
        fontSize: 10,
        textAlign: "center",
        color: "#94a3b8",
    },
});

// 2. Define the PDF Component
interface ProposalPDFProps {
    content: string;
    companyName: string;
    clientName: string;
}
// Add a helper function at the top of the file (outside component)
const cleanText = (text: string) => {
    return text
        .replace(/#/g, "") // Remove hashtags
        .replace(/\*\*/g, "") // Remove bolding stars
        .replace(/\*/g, "•") // Replace list stars with bullet points
        .replace(/\|/g, ""); // Remove any accidental table pipes
};
export const ProposalPDF = ({ content, companyName, clientName }: ProposalPDFProps) => (
    <Document>
        <Page size="A4" style={styles.page}>

            {/* Header Section */}
            <View style={styles.header}>
                <Text style={styles.companyName}>{companyName}</Text>
                <Text style={styles.clientName}>Prepared for: {clientName}</Text>
                <Text style={styles.clientName}>Date: {new Date().toLocaleDateString()}</Text>
            </View>

            {/* Main Content (The AI Text) */}
            {/* Note: We strip the '#' markdown symbols for a cleaner look in MVP */}
            <View style={styles.body}>
                <Text>{cleanText(content)}</Text>
            </View>

            {/* Footer */}
            <Text style={styles.footer}>
                Generated by FoundrKit - {companyName}
            </Text>
        </Page>
    </Document>
);